#echo -e "${color} Start Redis Server${nocolor}"
#systemctl enable redis &>>$log_file
#systemctl restart redis &>>$log_file
#stat_check $?
- name: installing Redis repo
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
- name: Installing Redis
  ansible.builtin.shell: yum module enable redis:remi-6.2
  ansible.builtin.yum:
    name: redis
    state: installed

- name: Updating redis listen address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Updating redis listen address
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start Redis Server
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes




