- name: Downloading Erlang
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: Downloading Rabitmq
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Installing Rabbitmq
  ansible.builtin.yum:
    name: rabbitmq-server
    state: installed

- name: Starting Rabitmq server
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes
- name: Adding Username and password
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present


#echo -e "${color} Adding Username and password ${nocolor}"
#rabbitmqctl add_user roboshop roboshop123 &>>/tmp/roboshop.log
#rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*" &>>/tmp/roboshop.log
#stat_check $?