#echo -e "\e[33m mysql server starting \e[0m"
#systemctl enable mysqld &>>$log_file
#systemctl restart mysqld &>>$log_file
#stat_check $?
#
#echo -e "\e[33m seting up  passwd \e[0m"
#mysql_secure_installation --set-root-pass $1 &>>$log_file
#stat_check $?
- name: Disabling mysql older version
  ansible.builtin.shell: yum module disable mysql

- name: Copy MySQL repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Installing mysql community server
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: mysql server starting
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enable: yes

- name: seting up  passwd
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1