- name: Installing Maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: load app_presetup
  ansible.builtin.import_tasks:
    file: app_presetup.yml

- name: Download Maven dependecies
  ansible.builtin.shell: mvn clean package ; mv target/{{ component }}-1.0.jar {{ component }}.yml
  args:
    chdir: /app

- name: load mysql schema setup
  ansible.builtin.import_tasks:
    file: mysql_schema_setup.yml

- name: Systemd setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml


