#echo -e "${color} Copy MongoDB Repo file ${nocolor}"
#cp /home/centos/roboshop-shell/mongodb.repo /etc/yum.repos.d/mongodb.repo  &>>$log_file
#stat_check $?
#
#echo -e "${color} Install MongoDB Client ${nocolor}"
#yum install mongodb-org-shell -y  &>>$log_file
#stat_check $?
#
#echo -e "${color} Load Schema ${nocolor}"
#mongo --host mongodb-dev.arshadev.online <${app_path}/schema/$component.js  &>>$log_file
#stat_check $?

- name: Copy MongoDB Repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB Client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Load Schema
  ansible.builtin.shell: mongo --host mongodb-dev.arshadev.online </app/schema/{{ component }}.js
