#echo -e "${color} Installing Mysql client ${nocolor}"
#yum install mysql -y &>>$log_file
#stat_check $?
#echo -e "${color} Loading Schema ${nocolor}"
#mysql -h mysql-dev.arshadev.online -uroot -p${mysql_root_password} <${app_path}/schema/$component.sql &>>$log_file
#stat_check $?

- name: Installing Mysql client
  ansible.builtin.yum:
    name: mysql
    state: installed

- name: Loading Mysql Schema
  ansible.builtin.shell: mysql -h mysql-dev.arshadev.online -uroot -pRoboShop@1 </app/schema/{{ component }}.sql
