- name: Configuring the NodeJS
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Installing the NodeJS
  ansible.builtin.yum:
    - name: nodejs
      state: installed







#app_presetup
#
#echo -e "${color} installing Nodejs Dependencies ${nocolor}"
#npm install &>>$log_file
#stat_check $?
#systemd_setup