- name: Configuring the NodeJS
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install the NodeJS
  ansible.builtin.yum:
     name: nodejs
     state: installed

- name: load app_presetup
  ansible.builtin.import_tasks:
    file: app_presetup.yml







#app_presetup
#
#echo -e "${color} installing Nodejs Dependencies ${nocolor}"
#npm install &>>$log_file
#stat_check $?
#systemd_setup