- name: Installing Python36
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: load app_presetup
  ansible.builtin.import_tasks:
    file: app_presetup.yml

- name: Downloading and Installing Dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: Systemd setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml